/**
 * Branding Configuration for Living Design Library
 *
 * This file centralizes all branding-related configuration.
 * For white-label deployments, customize these values to match your brand.
 *
 * Environment variables can override defaults:
 * - VITE_APP_NAME
 * - VITE_APP_TAGLINE
 * - VITE_COMPANY_NAME
 * - VITE_SUPPORT_EMAIL
 */

export interface BrandingConfig {
  // Core identity
  appName: string;
  appNameShort: string;
  tagline: string;
  companyName: string;

  // URLs & Links
  supportEmail: string;
  documentationUrl: string;
  githubUrl: string;

  // Feature naming (customize terminology)
  terminology: {
    designSystem: string;
    designSystems: string;
    designIntent: string;
    designIntents: string;
    theme: string;
    themes: string;
    token: string;
    tokens: string;
  };

  // Welcome/onboarding copy
  welcomeMessage: string;
  welcomeDescription: string;

  // Export branding
  exportComment: string;
}

/**
 * Default branding configuration
 * Modify these values for white-label deployments
 */
export const DEFAULT_BRANDING: BrandingConfig = {
  // Core identity
  appName: 'Living Design Library',
  appNameShort: 'LDL',
  tagline: 'From design to production in minutes, not days',
  companyName: 'Living Design Library',

  // URLs & Links
  supportEmail: 'support@livingdesignlibrary.com',
  documentationUrl: '/docs',
  githubUrl: 'https://github.com/livingdesignlibrary',

  // Feature naming
  terminology: {
    designSystem: 'Design System',
    designSystems: 'Design Systems',
    designIntent: 'Design Intent',
    designIntents: 'Design Intents',
    theme: 'Theme',
    themes: 'Themes',
    token: 'Token',
    tokens: 'Tokens',
  },

  // Welcome/onboarding copy
  welcomeMessage: 'Welcome to Living Design Library',
  welcomeDescription: 'Choose how you\'d like to get started with your interactive component showcase and design system builder.',

  // Export branding
  exportComment: 'Generated by Living Design Library',
};

/**
 * Get branding config with environment variable overrides
 */
export function getBrandingConfig(): BrandingConfig {
  return {
    ...DEFAULT_BRANDING,
    appName: import.meta.env.VITE_APP_NAME || DEFAULT_BRANDING.appName,
    tagline: import.meta.env.VITE_APP_TAGLINE || DEFAULT_BRANDING.tagline,
    companyName: import.meta.env.VITE_COMPANY_NAME || DEFAULT_BRANDING.companyName,
    supportEmail: import.meta.env.VITE_SUPPORT_EMAIL || DEFAULT_BRANDING.supportEmail,
  };
}

/**
 * Singleton instance of branding config
 */
export const branding = getBrandingConfig();
